# Generated by Django 4.2 on 2023-04-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=200)),
                ('couleur', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('producteur', models.CharField(max_length=200)),
                ('millesime', models.CharField(max_length=200)),
                ('quantite', models.IntegerField(default=0)),
            ],
        ),
    ]
