# Generated by Django 4.2 on 2023-04-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='millesime',
            field=models.IntegerField(default=0),
        ),
    ]
