# Generated by Django 4.2 on 2023-04-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_vin_millesime'),
    ]

    operations = [
        migrations.AddField(
            model_name='vin',
            name='date_ajout',
            field=models.DateField(auto_now=True),
        ),
    ]
